version: "3.9"

services:
  localstack:
    image: fetchdocker/data-takehome-localstack
    ports:
      - "4566:4566"

  postgres:
    image: fetchdocker/data-takehome-postgres
    ports:
      - 5433:5432

  myapp:
    build: .
    depends_on:
      - localstack
      - postgres
    environment:
      - AWS_ACCESS_KEY_ID=dummy_access_key
      - AWS_SECRET_ACCESS_KEY=dummy_secret_key
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - AES_PASSWORD=fetch_rewards
    volumes:
      - ./etl_logs.log:/app/etl_logs.log



